# Generated by Django 6.0.1 on 2026-01-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(
                help_text="Укажите номер телефона", verbose_name="Номер телефона"
            ),
        ),
    ]
