# Generated by Django 6.0.1 on 2026-01-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                help_text="Укажите номер телефона", verbose_name="Номер телефона"
            ),
        ),
    ]
