# Generated by Django 6.0.1 on 2026-01-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="users",
            new_name="user",
        ),
    ]
